NUMPY PROBLEMS

In [2]:
import numpy as np

1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

In [2]:
my_list = [12.23, 13.32, 100, 36.32]

my_array = np.array(my_list)

print(my_array)
print(type(my_array))

[ 12.23  13.32 100.    36.32]
<class 'numpy.ndarray'>


2. Create a 3x3 matrix with values ranging from 2 to 10.

In [3]:
my_array = np.arange(2,11)

my_matrix = my_array.reshape(3,3)

print(my_matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [5]:
null_vector = np.zeros(10)

null_vector[5] = 11

print("Updated vector:", null_vector)

Updated vector: [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).

In [6]:
my_array = np.arange(12,38)

my_array = my_array[::-1]

print(my_array)

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [33]:
matrix_of_1 = np.ones((5,5))

print(matrix_of_1)

# The slicing syntax follows the format array[start:stop:step, start:stop:step, ...]
# matrix_of_1[1:-1, :] = 0
# matrix_of_1[:, 1:-1] = 0
# matrix_of_1[1:-1,1:-1] = 0 or matrix_of_1[1:4, 1:4]

matrix_of_1[1:-1,1:-1] = 0
print(matrix_of_1)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.

In [34]:
arr = np.ones((3, 3))

print("Original array:")
print(arr)

arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print("\nArray with a border of 0's:")
print(arr_with_border)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with a border of 0's:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [40]:
matrix = np.zeros((8, 8), dtype=int)

# Rows 1, 3, 5 (odd rows) and columns 0, 2, 4 (even columns)
matrix[1::2, ::2] = 1  

# Rows 0, 2, 4 (even rows) and columns 1, 3, 5 (odd columns)
matrix[::2, 1::2] = 1  

# Display the result
print("Matrix with alternating zeros and ones:")
print(matrix)


Matrix with alternating zeros and ones:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays

In [41]:
list_to_array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("List to array:")
print(list_to_array)

tuple_to_array = np.array([(8, 4, 6), (1, 2, 3)])
print("Tuple to array:")
print(tuple_to_array)

List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.

In [43]:
arr = np.array([10, 20, 30])

arr = np.append(arr,[40, 50, 60, 70, 80, 90])

print(arr)

[10 20 30 40 50 60 70 80 90]


10.Write a Python program to find the real and imaginary parts of an array of complex numbers.

In [47]:
complex_array = np.array([1.00000000+0.j , 0.70710678+0.70710678j])

print("Original complex array:")
print(complex_array)

# Extract the real part
real_part = complex_array.real
print("\nReal part of the array:")
print(real_part)

# Extract the imaginary part
imaginary_part = complex_array.imag
print("\nImaginary part of the array:")
print(imaginary_part)


Original complex array:
[1.        +0.j         0.70710678+0.70710678j]

Real part of the array:
[1.         0.70710678]

Imaginary part of the array:
[0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.

In [48]:
array = np.array([1, 2, 3])

num_elements = array.size

element_size = array.itemsize

total_bytes = num_elements * element_size

print("Size of the array: ", num_elements)
print("Length of one array element in bytes: ", element_size)
print("Total bytes consumed by the elements of the array:", total_bytes)


Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array: 24


12. Write a Python program to find common values between two arrays.

In [49]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])

common_values = np.intersect1d(array1, array2)

print("Common values between the two arrays:")
print(common_values)


Common values between the two arrays:
[10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.

In [51]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70, 90])

set_difference = np.setdiff1d(array1, array2)

print("Set difference between two arrays: ")
print(set_difference)

Set difference between two arrays: 
[ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.

In [52]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])

exclusive_or = np.setxor1d(array1, array2)


print("Set exclusive-or (elements in only one of the arrays):")
print(exclusive_or)

Set exclusive-or (elements in only one of the arrays):
[ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.

In [53]:
a = np.array([1, 2])
b = np.array([4, 5])

greater_than = a > b
greater_than_or_equal = a >= b
less_than = a < b
less_than_or_equal = a <= b

print("Array a:", a)
print("Array b:", b)
print("a > b:", greater_than)             
print("a >= b:", greater_than_or_equal)   
print("a < b:", less_than)                 
print("a <= b:", less_than_or_equal)      

Array a: [1 2]
Array b: [4 5]
a > b: [False False]
a >= b: [False False]
a < b: [ True  True]
a <= b: [ True  True]


15B. Write a Python program to save a NumPy array to a text file.

In [55]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

filename = 'array.txt'

np.savetxt(filename, array, delimiter=',', fmt='%d')

print(f"Array saved to {filename}.")

Array saved to array.txt.


16. Write a Python program to create a contiguous flattened array.

In [62]:
array_2d = np.array([[10, 20, 30], [20, 40, 50]])

# Create a contiguous flattened array using ravel
flattened_ravel = np.ravel(array_2d)

# Create a contiguous flattened array using flatten
flattened_flatten = array_2d.flatten()

# Display the original array and the flattened arrays
print("Original 2D array:")
print(array_2d)
print("\nContiguous flattened array using ravel:")
print(flattened_ravel)
print("\nContiguous flattened array using flatten:")
print(flattened_flatten)

Original 2D array:
[[10 20 30]
 [20 40 50]]

Contiguous flattened array using ravel:
[10 20 30 20 40 50]

Contiguous flattened array using flatten:
[10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.

In [61]:
array1 = np.array([[2, 4, 6],[6, 8, 10]])
print(f"{array1} data type is {array1.dtype}")

array1 = array1.astype(float)

print(f"\n{array1} data type is {array1.dtype}")

[[ 2  4  6]
 [ 6  8 10]] data type is int64

[[ 2.  4.  6.]
 [ 6.  8. 10.]] data type is float64


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.

In [63]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.

In [66]:
array = np.zeros((4, 3))

# array[1, 0] = 1
# array[2, 0:2] = 1
# array[3, 0:3] = 1

for i in range(1, 4):
    array[i, :i] = 1

print(array)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.

In [67]:
array1 = np.array([[0, 1, 3], [5, 7, 9]])
array2 = np.array([[0, 2, 4], [6, 8, 10]])

result = np.concatenate((array1, array2), axis=1)

print("Concatenated array:")
print(result)


Concatenated array:
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only)

In [69]:
arr = np.array([1, 2, 3, 4])

arr.flags.writeable = False


print("Read-only array:")
print(arr)
arr[0] = 10


Read-only array:
[1 2 3 4]


ValueError: assignment destination is read-only

22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array

In [84]:
my_matrix = np.arange(12)
my_matrix = my_matrix.reshape(3,4)
my_matrix = my_matrix * 3
print(my_matrix)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.

In [87]:
my_array = np.arange(6)
my_array = my_array.reshape(3,2)

my_list = my_array.tolist()
print(my_array, type(my_array))
print(my_array, type(my_list))

[[0 1]
 [2 3]
 [4 5]] <class 'numpy.ndarray'>
[[0 1]
 [2 3]
 [4 5]] <class 'list'>


24. Write a Python program to convert a NumPy array into Python list structure.Print array values with precision 3

In [3]:
array = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067, 
                  0.7831874, 0.69746349, 0.35399976, 0.99469633, 
                  0.0694458, 0.54711478])

array_as_list = array.tolist()

print(array_as_list)

np.set_printoptions(precision=3)

formatted_list = [f"{x:.3f}" for x in array_as_list]

print(formatted_list)
print(array)


[0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478]
['0.262', '0.528', '0.572', '0.593', '0.783', '0.697', '0.354', '0.995', '0.069', '0.547']
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.

In [4]:
array = np.array([1.6e-10, 1.6e+00, 1.2e+03, 2.35e-01])

# Suppress scientific notation and set the precision to 3 decimal places
# np.set_printoptions(suppress=True) tells NumPy not to use scientific notation for small numbers.
np.set_printoptions(suppress=True, precision=3)
print("Array values with precision 3:")
print(array)

Array values with precision 3:
[   0.       1.6   1200.       0.235]


26. Write a Python program to how to add an extra column to an numpy array

In [6]:
array = np.array([[10, 20, 30], [40, 50, 60]])

new_column = np.array([[100], [200]])
result = np.hstack((array, new_column))
print("Array after adding a new column:")
print(result)

Array after adding a new column:
[[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array

In [5]:
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
indices_to_remove = [0, 3, 4]

new_array = np.delete(array, indices_to_remove)
print("Array after deleting specific elements:")
print(new_array)

Array after deleting specific elements:
[ 20  30  60  70  80  90 100]
